import Nav from "./auth/Nav";
import { Roboto } from "next/font/google";
import QueryWrap from "./auth/QueryWrap";
import "./global.css";


//global file
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`mx-4 md:mx-48 xl:mx-96${roboto.variable} bg-gray-200`}>
        <QueryWrap>
          <Nav />
          {children}
        </QueryWrap>
      </body>
    </html>
  );
}
